// Workflow Engine HTTP API.
//
//	@title			Workflow Engine API
//	@version		1.0
//	@description	Multi-tenant workflow engine (projects, workflows). Regenerate docs with: go generate ./cmd/api/...
//
//	@host		localhost:8080
//	@BasePath	/
//	@schemes	http
//
//	@securityDefinitions.apikey	ApiKeyAuth
//	@in							header
//	@name						Authorization
//	@description				Use: Bearer wf_yourPrefix.yourSecret
package main

//go:generate go run github.com/swaggo/swag/cmd/swag@v1.16.6 init -g main.go -o ../../docs -d .,../../internal/interfaces/http,../../internal/infrastructure/db/models --parseInternal

import (
	"context"
	"log"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/SheykoWk/workflow-engine/internal/infrastructure/db"
	httpapi "github.com/SheykoWk/workflow-engine/internal/interfaces/http"
	"github.com/joho/godotenv"

	_ "github.com/SheykoWk/workflow-engine/docs" // OpenAPI spec generated by swag (see docs.go).
)

func main() {
	// Go only reads the process environment (os.Getenv). A .env file is not loaded
	// automatically; godotenv copies its KEY=value pairs into the environment.
	if _, err := os.Stat(".env"); err == nil {
		if err := godotenv.Load(); err != nil {
			log.Fatalf("load .env: %v", err)
		}
	}

	databaseURL := os.Getenv("DATABASE_URL")
	if databaseURL == "" {
		log.Fatal("DATABASE_URL is required")
	}

	sqlDB, err := db.OpenSQL(context.Background(), databaseURL)
	if err != nil {
		log.Fatalf("database: %v", err)
	}
	defer func() { _ = sqlDB.Close() }()

	workflowRepo := db.NewWorkflowRepository(sqlDB)
	projectRepo := db.NewProjectRepository(sqlDB)
	apiKeyRepo := db.NewAPIKeyRepository(sqlDB)
	workflows := httpapi.NewWorkflowHandler(workflowRepo)
	projects := httpapi.NewProjectHandler(projectRepo)

	addr := ":8080"
	if v := os.Getenv("HTTP_ADDR"); v != "" {
		addr = v
	}

	handler := httpapi.NewRouter(apiKeyRepo, workflows, projects)
	srv := &http.Server{
		Addr:    addr,
		Handler: handler,
	}

	go func() {
		log.Printf("listening on %s", addr)
		if err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			log.Fatalf("server: %v", err)
		}
	}()

	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit
	log.Printf("shutting down server...")

	shutdownCtx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	if err := srv.Shutdown(shutdownCtx); err != nil {
		log.Printf("server shutdown: %v", err)
	}
	log.Printf("server stopped")
}
